#include <stdio.h>
#include <string.h>

#include "content.h"
#include "util.h"

static char g_content_error[256];
static char g_content_message[256];
static char g_list_line[MAX_LINE];
static char g_body_line[MAX_LINE];
static char g_list_seen_names[MAX_POSTS > MAX_PAGES ? MAX_POSTS : MAX_PAGES][16];
static char g_list_path[MAX_LINE];
static char g_parse_line[MAX_LINE];
static char g_parse_key[64];
static char g_parse_value[MAX_TEXT];
static Post g_post_scratch;
static Page g_page_scratch;

static void init_site_config(SiteConfig *config) {
    copy_string(config->title, sizeof(config->title), "Local Zine");
    config->banner[0] = '\0';
    copy_string(config->theme, sizeof(config->theme), "vga");
    copy_string(config->tagline, sizeof(config->tagline), "A DOS-native static blog generator.");
    copy_string(config->description, sizeof(config->description), "A multi-page blog generated by a 16-bit DOS executable.");
    copy_string(config->about, sizeof(config->about), "Local Zine is a starter DOS blog generator.");
}

static void init_post(Post *post) {
    post->title[0] = '\0';
    post->slug[0] = '\0';
    post->date[0] = '\0';
    copy_string(post->category, sizeof(post->category), "notes");
    post->summary[0] = '\0';
    post->tags[0] = '\0';
    post->draft = 0;
    post->has_body = 0;
    post->body_offset = -1L;
    post->output_name[0] = '\0';
    post->source_name[0] = '\0';
    post->source_path[0] = '\0';
}

static void init_page(Page *page) {
    page->title[0] = '\0';
    page->slug[0] = '\0';
    page->summary[0] = '\0';
    page->tags[0] = '\0';
    page->draft = 0;
    page->has_body = 0;
    page->body_offset = -1L;
    page->output_name[0] = '\0';
    page->source_name[0] = '\0';
    page->source_path[0] = '\0';
}

static void set_content_error(const char *message) {
    copy_string(g_content_error, sizeof(g_content_error), message);
}

static int copy_field_value(char *dest, int dest_size, const char *value, const char *field_name, const char *path) {
    if ((int)strlen(value) >= dest_size) {
        sprintf(g_content_message, "Value too long for %s in %s", field_name, path);
        set_content_error(g_content_message);
        return 0;
    }

    copy_string(dest, dest_size, value);
    return 1;
}

static int append_field_line(char *dest, int dest_size, const char *line, const char *field_name, const char *path) {
    if (dest[0] != '\0' && !append_string_checked(dest, dest_size, "\n")) {
        sprintf(g_content_message, "%s too long in %s", field_name, path);
        set_content_error(g_content_message);
        return 0;
    }

    if (!append_string_checked(dest, dest_size, line)) {
        sprintf(g_content_message, "%s too long in %s", field_name, path);
        set_content_error(g_content_message);
        return 0;
    }

    return 1;
}

static int is_site_config_key(const char *key) {
    return strings_equal(key, "title") ||
        strings_equal(key, "banner") ||
        strings_equal(key, "theme") ||
        strings_equal(key, "tagline") ||
        strings_equal(key, "description") ||
        strings_equal(key, "about");
}

static int validate_post(const Post *post, const char *path) {
    if (post->title[0] == '\0') {
        sprintf(g_content_message, "Missing title in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    if (post->slug[0] == '\0') {
        sprintf(g_content_message, "Missing slug in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    if (!is_valid_dos_slug(post->slug)) {
        sprintf(g_content_message, "Invalid DOS slug '%s' in %s", post->slug, path);
        set_content_error(g_content_message);
        return 0;
    }

    if (!strings_equal_ignore_case(post->source_name, "")) {
        char expected[16];
        make_source_filename(expected, sizeof(expected), post->slug);
        if (!strings_equal_ignore_case(post->source_name, expected)) {
            sprintf(g_content_message, "Slug '%s' must match source file %s in %s", post->slug, expected, path);
            set_content_error(g_content_message);
            return 0;
        }
    }

    if (post->date[0] == '\0') {
        sprintf(g_content_message, "Missing date in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    if (!post->has_body || post->body_offset < 0) {
        sprintf(g_content_message, "Missing body in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    return 1;
}

static int validate_page(const Page *page, const char *path) {
    if (page->title[0] == '\0') {
        sprintf(g_content_message, "Missing title in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    if (page->slug[0] == '\0') {
        sprintf(g_content_message, "Missing slug in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    if (!is_valid_dos_slug(page->slug)) {
        sprintf(g_content_message, "Invalid DOS slug '%s' in %s", page->slug, path);
        set_content_error(g_content_message);
        return 0;
    }

    if (!strings_equal_ignore_case(page->source_name, "")) {
        char expected[16];
        make_source_filename(expected, sizeof(expected), page->slug);
        if (!strings_equal_ignore_case(page->source_name, expected)) {
            sprintf(g_content_message, "Slug '%s' must match source file %s in %s", page->slug, expected, path);
            set_content_error(g_content_message);
            return 0;
        }
    }

    if (!page->has_body || page->body_offset < 0) {
        sprintf(g_content_message, "Missing body in %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    return 1;
}

static int parse_key_value(const char *line, char *key, int key_size, char *value, int value_size) {
    const char *colon = strchr(line, ':');

    if (colon == NULL) {
        return 0;
    }

    if (colon == line) {
        return 0;
    }

    copy_range_string(key, key_size, line, colon);
    trim_whitespace(key);

    ++colon;
    while (*colon == ' ' || *colon == '\t') {
        ++colon;
    }

    copy_string(value, value_size, colon);
    trim_whitespace(value);
    return 1;
}

int load_site_config(const char *path, SiteConfig *config) {
    FILE *fp;
    int in_about;

    init_site_config(config);
    g_content_error[0] = '\0';
    fp = open_existing_file(path, "r");
    if (fp == NULL) {
        set_content_error("Failed to open site.txt");
        return 0;
    }

    in_about = 0;
    config->about[0] = '\0';

    while (fgets(g_parse_line, sizeof(g_parse_line), fp) != NULL) {
        trim_line_endings(g_parse_line);

        if (in_about) {
            if (!parse_key_value(g_parse_line, g_parse_key, sizeof(g_parse_key), g_parse_value, sizeof(g_parse_value)) || !is_site_config_key(g_parse_key)) {
                if (!append_field_line(config->about, sizeof(config->about), g_parse_line, "about", path)) {
                    fclose(fp);
                    return 0;
                }
                continue;
            }

            in_about = 0;
        }

        if (g_parse_line[0] == '\0') {
            continue;
        }

        if (!parse_key_value(g_parse_line, g_parse_key, sizeof(g_parse_key), g_parse_value, sizeof(g_parse_value))) {
            continue;
        }

        if (strings_equal(g_parse_key, "title")) {
            if (!copy_field_value(config->title, sizeof(config->title), g_parse_value, "title", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "banner")) {
            if (!copy_field_value(config->banner, sizeof(config->banner), g_parse_value, "banner", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "theme")) {
            if (!copy_field_value(config->theme, sizeof(config->theme), g_parse_value, "theme", path)) {
                fclose(fp);
                return 0;
            }
            lowercase_string(config->theme);
            if (!strings_equal(config->theme, "vga") &&
                    !strings_equal(config->theme, "win98") &&
                    !strings_equal(config->theme, "crt")) {
                sprintf(g_content_message, "Invalid theme '%s' in %s", config->theme, path);
                set_content_error(g_content_message);
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "tagline")) {
            if (!copy_field_value(config->tagline, sizeof(config->tagline), g_parse_value, "tagline", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "description")) {
            if (!copy_field_value(config->description, sizeof(config->description), g_parse_value, "description", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "about")) {
            if (!copy_field_value(config->about, sizeof(config->about), g_parse_value, "about", path)) {
                fclose(fp);
                return 0;
            }
            in_about = 1;
        }
    }

    fclose(fp);
    return 1;
}

static int load_post_file(const char *path, const char *source_name, Post *post) {
    FILE *fp;
    int in_body;

    init_post(post);
    copy_string(post->source_name, sizeof(post->source_name), source_name);
    copy_string(post->source_path, sizeof(post->source_path), path);

    fp = open_existing_file(path, "r");
    if (fp == NULL) {
        sprintf(g_content_message, "Failed to open %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    in_body = 0;

    while (fgets(g_parse_line, sizeof(g_parse_line), fp) != NULL) {
        trim_line_endings(g_parse_line);

        if (in_body) {
            if (g_parse_line[0] != '\0') {
                post->has_body = 1;
            }
            continue;
        }

        if (g_parse_line[0] == '\0') {
            post->body_offset = ftell(fp);
            in_body = 1;
            continue;
        }

        if (!parse_key_value(g_parse_line, g_parse_key, sizeof(g_parse_key), g_parse_value, sizeof(g_parse_value))) {
            continue;
        }

        if (strings_equal(g_parse_key, "title")) {
            if (!copy_field_value(post->title, sizeof(post->title), g_parse_value, "title", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "slug")) {
            if (!copy_field_value(post->slug, sizeof(post->slug), g_parse_value, "slug", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "date")) {
            if (!copy_field_value(post->date, sizeof(post->date), g_parse_value, "date", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "category")) {
            if (!copy_field_value(post->category, sizeof(post->category), g_parse_value, "category", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "summary")) {
            if (!copy_field_value(post->summary, sizeof(post->summary), g_parse_value, "summary", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "tags")) {
            if (!copy_field_value(post->tags, sizeof(post->tags), g_parse_value, "tags", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "draft")) {
            post->draft = strings_equal_ignore_case(g_parse_value, "yes") || strings_equal_ignore_case(g_parse_value, "true") || strings_equal(g_parse_value, "1");
        }
    }

    normalize_slug(post->slug, sizeof(post->slug), post->slug);
    normalize_slug(post->category, sizeof(post->category), post->category);
    make_output_name(post->output_name, sizeof(post->output_name), post->slug);
    fclose(fp);
    return validate_post(post, path);
}

static int load_page_file(const char *path, const char *source_name, Page *page) {
    FILE *fp;
    int in_body;

    init_page(page);
    copy_string(page->source_name, sizeof(page->source_name), source_name);
    copy_string(page->source_path, sizeof(page->source_path), path);

    fp = open_existing_file(path, "r");
    if (fp == NULL) {
        sprintf(g_content_message, "Failed to open %s", path);
        set_content_error(g_content_message);
        return 0;
    }

    in_body = 0;

    while (fgets(g_parse_line, sizeof(g_parse_line), fp) != NULL) {
        trim_line_endings(g_parse_line);

        if (in_body) {
            if (g_parse_line[0] != '\0') {
                page->has_body = 1;
            }
            continue;
        }

        if (g_parse_line[0] == '\0') {
            page->body_offset = ftell(fp);
            in_body = 1;
            continue;
        }

        if (!parse_key_value(g_parse_line, g_parse_key, sizeof(g_parse_key), g_parse_value, sizeof(g_parse_value))) {
            continue;
        }

        if (strings_equal(g_parse_key, "title")) {
            if (!copy_field_value(page->title, sizeof(page->title), g_parse_value, "title", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "slug")) {
            if (!copy_field_value(page->slug, sizeof(page->slug), g_parse_value, "slug", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "summary")) {
            if (!copy_field_value(page->summary, sizeof(page->summary), g_parse_value, "summary", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "tags")) {
            if (!copy_field_value(page->tags, sizeof(page->tags), g_parse_value, "tags", path)) {
                fclose(fp);
                return 0;
            }
        } else if (strings_equal(g_parse_key, "draft")) {
            page->draft = strings_equal_ignore_case(g_parse_value, "yes") || strings_equal_ignore_case(g_parse_value, "true") || strings_equal(g_parse_value, "1");
        }
    }

    normalize_slug(page->slug, sizeof(page->slug), page->slug);
    make_output_name(page->output_name, sizeof(page->output_name), page->slug);
    fclose(fp);
    return validate_page(page, path);
}

static int validate_unique_post_slugs(const Post *posts, int count) {
    int i;
    int j;
    char message[256];

    for (i = 0; i < count; ++i) {
        for (j = i + 1; j < count; ++j) {
            if (strings_equal_ignore_case(posts[i].slug, posts[j].slug)) {
                sprintf(message, "Duplicate post slug '%s'", posts[i].slug);
                set_content_error(message);
                return 0;
            }
        }
    }

    return 1;
}

static int validate_unique_page_slugs(const Page *pages, int count) {
    int i;
    int j;
    char message[256];

    for (i = 0; i < count; ++i) {
        for (j = i + 1; j < count; ++j) {
            if (strings_equal_ignore_case(pages[i].slug, pages[j].slug)) {
                sprintf(message, "Duplicate page slug '%s'", pages[i].slug);
                set_content_error(message);
                return 0;
            }
        }
    }

    return 1;
}

static int load_entry_list(const char *list_path, const char *folder, int is_post, void *items, int max_items) {
    FILE *fp;
    int seen_count;
    int published_count;

    fp = open_existing_file(list_path, "r");
    if (fp == NULL) {
        if (is_post) {
            set_content_error("Failed to open posts.lst");
            return -1;
        }
        return 0;
    }

    seen_count = 0;
    published_count = 0;

    while (fgets(g_list_line, sizeof(g_list_line), fp) != NULL) {
        char normalized_name[16];
        int i;

        trim_line_endings(g_list_line);
        trim_whitespace(g_list_line);

        if (g_list_line[0] == '\0' || g_list_line[0] == '#') {
            continue;
        }

        if (!is_valid_list_entry_name(g_list_line)) {
            char message[256];
            sprintf(message, "Invalid list entry '%s' in %s", g_list_line, list_path);
            set_content_error(message);
            fclose(fp);
            return -1;
        }

        copy_string(normalized_name, sizeof(normalized_name), g_list_line);
        lowercase_string(normalized_name);

        for (i = 0; i < seen_count; ++i) {
            if (strings_equal_ignore_case(g_list_seen_names[i], normalized_name)) {
                char message[256];
                sprintf(message, "Duplicate list entry '%s' in %s", g_list_line, list_path);
                set_content_error(message);
                fclose(fp);
                return -1;
            }
        }

        if (seen_count < (int)(sizeof(g_list_seen_names) / sizeof(g_list_seen_names[0]))) {
            copy_string(g_list_seen_names[seen_count], sizeof(g_list_seen_names[seen_count]), normalized_name);
            ++seen_count;
        }

        join_path(g_list_path, sizeof(g_list_path), folder, normalized_name);

        if (is_post) {
            if (!load_post_file(g_list_path, normalized_name, &g_post_scratch)) {
                fclose(fp);
                return -1;
            }
            if (!g_post_scratch.draft) {
                if (published_count >= max_items) {
                    char message[256];
                    sprintf(message, "Too many posts; maximum is %d", max_items);
                    set_content_error(message);
                    fclose(fp);
                    return -1;
                }
                sprintf(g_post_scratch.output_name, "P%04d.HTM", published_count + 1);
                ((Post *)items)[published_count++] = g_post_scratch;
            }
        } else {
            if (!load_page_file(g_list_path, normalized_name, &g_page_scratch)) {
                fclose(fp);
                return -1;
            }
            if (!g_page_scratch.draft) {
                if (published_count >= max_items) {
                    char message[256];
                    sprintf(message, "Too many pages; maximum is %d", max_items);
                    set_content_error(message);
                    fclose(fp);
                    return -1;
                }
                ((Page *)items)[published_count++] = g_page_scratch;
            }
        }
    }

    fclose(fp);
    return published_count;
}

int load_posts(const char *list_path, Post *posts, int max_posts) {
    int count;

    count = load_entry_list(list_path, "posts", 1, posts, max_posts);
    if (count < 0) {
        return -1;
    }

    if (!validate_unique_post_slugs(posts, count)) {
        return -1;
    }

    return count;
}

int load_pages(const char *list_path, Page *pages, int max_pages) {
    int count;

    count = load_entry_list(list_path, "pages", 0, pages, max_pages);
    if (count < 0) {
        return -1;
    }

    if (!validate_unique_page_slugs(pages, count)) {
        return -1;
    }

    return count;
}

int validate_post_page_output_names(const Post *posts, int post_count, const Page *pages, int page_count) {
    (void)posts;
    (void)post_count;
    (void)pages;
    (void)page_count;
    return 1;
}

static int load_body_from_file(const char *path, long body_offset, char *body, int body_size) {
    FILE *fp;

    body[0] = '\0';

    fp = open_existing_file(path, "r");
    if (fp == NULL) {
        char message[256];
        sprintf(message, "Failed to open %s", path);
        set_content_error(message);
        return 0;
    }

    if (body_offset >= 0 && fseek(fp, body_offset, SEEK_SET) != 0) {
        char message[256];
        sprintf(message, "Failed to seek body in %s", path);
        set_content_error(message);
        fclose(fp);
        return 0;
    }

    while (fgets(g_body_line, sizeof(g_body_line), fp) != NULL) {
        trim_line_endings(g_body_line);
        if (!append_field_line(body, body_size, g_body_line, "body", path)) {
            fclose(fp);
            return 0;
        }
    }

    fclose(fp);
    return 1;
}

int load_post_body(const Post *post, char *body, int body_size) {
    return load_body_from_file(post->source_path, post->body_offset, body, body_size);
}

int load_page_body(const Page *page, char *body, int body_size) {
    return load_body_from_file(page->source_path, page->body_offset, body, body_size);
}

const char *get_content_error(void) {
    return g_content_error;
}
